#!/bin/bash

set -e
. /usr/share/debconf/confmodule

case "$1" in
  install)
    [ ! -f /var/lib/emc/.emercoin/emercoin.conf ] && { echo "Cannot stat /var/lib/emc/.emercoin/emercoin.conf"; exit 1; }
    mkdir -p /etc/emercoin/emcssh.keys.d
    chown root.emc /etc/emercoin/emcssh.keys.d
    chmod 770 /etc/emercoin/emcssh.keys.d
    grep "AuthorizedKeysCommand /usr/sbin/emcssh" /etc/ssh/sshd_config >/dev/null || {
      echo -e "\nAuthorizedKeysCommand /usr/sbin/emcssh\nAuthorizedKeysCommandUser root" >> /etc/ssh/sshd_config
      systemctl restart ssh || true
    }
    touch /var/tmp/emcssh-install.flag
  ;;
esac

exit 0
